# Generated by Django 5.0.2 on 2024-02-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=50)),
                ("error_message", models.TextField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
