# Generated by Django 5.0.2 on 2024-02-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap", "0002_errorpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bitstamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unix", models.IntegerField()),
                ("date", models.DateTimeField()),
                ("symbol", models.CharField(max_length=50)),
                ("open", models.IntegerField()),
                ("high", models.IntegerField()),
                ("low", models.IntegerField()),
                ("close", models.IntegerField()),
                ("volume_btc", models.DecimalField(decimal_places=10, max_digits=20)),
                ("volume_usd", models.DecimalField(decimal_places=10, max_digits=20)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
