# Generated by Django 5.0.2 on 2024-02-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap", "0004_alter_bitstamp_close_alter_bitstamp_high_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bitstamp",
            name="close",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name="bitstamp",
            name="high",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name="bitstamp",
            name="low",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name="bitstamp",
            name="open",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name="bitstamp",
            name="volume_btc",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name="bitstamp",
            name="volume_usd",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
