# Generated by Django 5.0.2 on 2024-02-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BitstampData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unix", models.IntegerField()),
                ("date", models.DateTimeField()),
                ("symbol", models.CharField(max_length=50)),
                ("open", models.DecimalField(decimal_places=10, max_digits=20)),
                ("high", models.DecimalField(decimal_places=10, max_digits=20)),
                ("low", models.DecimalField(decimal_places=10, max_digits=20)),
                ("close", models.DecimalField(decimal_places=10, max_digits=20)),
                ("volume_btc", models.DecimalField(decimal_places=10, max_digits=20)),
                ("volume_usd", models.DecimalField(decimal_places=10, max_digits=20)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommentRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_id", models.CharField(max_length=50)),
                ("post_id", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("comment_url", models.URLField()),
                ("comment_score", models.IntegerField()),
                ("comment_body", models.TextField()),
                ("author_name", models.CharField(max_length=100)),
                ("author_id", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ErrorPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=50)),
                ("error_message", models.TextField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=300)),
                ("raw_text", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("platform_source", models.CharField(max_length=10)),
                ("post_url", models.URLField()),
                ("author_name", models.CharField(max_length=300)),
                ("author_id", models.CharField(max_length=50)),
                ("post_score", models.IntegerField()),
            ],
        ),
    ]
