# Generated by Django 5.0.2 on 2024-02-25 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap", "0002_bitstampdatahour"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitstampdatahour",
            name="local_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
