# Generated by Django 5.0.2 on 2024-02-25 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap", "0003_bitstampdatahour_local_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitstampdata",
            name="local_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
