# Generated by Django 5.0.2 on 2024-02-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrap", "0004_bitstampdata_local_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("error_source", models.CharField(max_length=200)),
                ("error_type", models.CharField(max_length=200)),
                ("error_content", models.TextField()),
                ("error_message", models.TextField()),
            ],
        ),
    ]
